name: SpringBoot Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - './**'

jobs:
  build:

    permissions: write-all
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4.1.7
    
    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.2
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Maven Settings XML
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        repositories: ''
        servers: ''

    - name: Build with Maven
      run: mvn package -B -DskipTests --file ./pom.xml

    - name: GH Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./target/foreverserver-*.jar
        tag_name: ForeverServer-v1.0
